num = int(input('Digite um número para ver sua tabuada: '))
print('_' * 12)
print('{} x {:2} = {}'.format(num, 1, num*1))
print('{} x {:2} = {}'.format(num, 2, num*2))
print('{} x {:2} = {}'.format(num, 3, num*3))
print('{} x {:2} = {}'.format(num, 4, num*4))
print('{} x {:2} = {}'.format(num, 5, num*5))
print('{} x {:2} = {}'.format(num, 6, num*2))
print('{} x {:2} = {}'.format(num, 7, num*3))
print('{} x {:2} = {}'.format(num, 8, num*4))
print('{} x {:2} = {}'.format(num, 9, num*5))
print('{} x {:2} = {}'.format(num, 10, num*10))
print('_' * 12)

